"use client";
import {useEffect,useRef,useState} from "react";
import {CheckCircle2,ExternalLink,LocateFixed,LoaderCircle,MapPin,XCircle} from "lucide-react";
import {serviceAreas} from "@/data/serviceAreas";

type Result={available:boolean;nearest:string;distance:number}|null;
function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const r=6371;const dLat=(bLat-aLat)*Math.PI/180;const dLng=(bLng-aLng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}

export default function CoverageMap({children}:{children?:React.ReactNode}){
 const mapNode=useRef<HTMLDivElement>(null);const mapRef=useRef<import("leaflet").Map|null>(null);const userLayer=useRef<import("leaflet").Layer|null>(null);
 const [result,setResult]=useState<Result>(null);const [status,setStatus]=useState<"idle"|"loading"|"denied"|"unsupported">("idle");
 useEffect(()=>{let active=true;import("leaflet").then(L=>{if(!active||!mapNode.current||mapRef.current)return;const map=L.map(mapNode.current,{scrollWheelZoom:false}).setView([28.43,76.91],10);mapRef.current=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);const bounds:[number,number][]=[];serviceAreas.forEach(area=>{const point:[number,number]=[area.lat,area.lng];bounds.push(point);L.circle(point,{radius:15000,color:"#0782c5",weight:1,fillColor:"#1bb7d6",fillOpacity:.08}).addTo(map);L.circleMarker(point,{radius:7,color:"#fff",weight:2,fillColor:"#ff7a1a",fillOpacity:1}).addTo(map).bindPopup(`<strong>${area.name}</strong><br>Approx. 15 km service radius`)});map.fitBounds(bounds,{padding:[20,20]})});return()=>{active=false;if(mapRef.current){mapRef.current.remove();mapRef.current=null}}},[]);
 function locate(){if(!navigator.geolocation){setStatus("unsupported");return}setResult(null);setStatus("loading");navigator.geolocation.getCurrentPosition(async pos=>{const {latitude,longitude}=pos.coords;let nearest=serviceAreas[0];let min=Infinity;for(const a of serviceAreas){const d=distanceKm(latitude,longitude,a.lat,a.lng);if(d<min){min=d;nearest=a}}setResult({available:min<=15,nearest:nearest.name,distance:min});setStatus("idle");const L=await import("leaflet");const map=mapRef.current;if(map){if(userLayer.current)map.removeLayer(userLayer.current);userLayer.current=L.circleMarker([latitude,longitude],{radius:9,color:"#fff",weight:3,fillColor:"#126b3a",fillOpacity:1}).addTo(map).bindPopup("Your current location").openPopup();map.setView([latitude,longitude],12)}},()=>setStatus("denied"),{enableHighAccuracy:true,timeout:12000,maximumAge:300000})}
 return <section className="coverage-map-section"><div className="coverage-heading"><span className="eyebrow dark">Live coverage map</span><h2>Check AC service near you</h2><p>Choose either automatic location detection or type your town, village or sector.</p></div><div className="coverage-split"><div className="map-column"><div className="coverage-map" ref={mapNode}/><a className="open-maps" href="https://www.google.com/maps/search/?api=1&query=Sector+86+Gurugram" target="_blank" rel="noreferrer"><ExternalLink/> Open in Maps</a></div><aside className="location-panel"><div className="location-panel-icon"><LocateFixed/></div><span className="eyebrow dark">Check availability</span><h3>Are we available at your place?</h3><p>Use your current position or enter a location manually. Both options check the same 15 km service areas.</p><button className="btn location-permission" onClick={locate} disabled={status==="loading"}>{status==="loading"?<LoaderCircle className="spin"/>:<LocateFixed/>}{status==="loading"?"Checking location…":"Use my current location"}</button><div className="permission-note"><MapPin/> Your precise location is used only for this availability check.</div>{result&&<div className={result.available?"geo-result available":"geo-result unavailable"}>{result.available?<CheckCircle2/>:<XCircle/>}<span><b>{result.available?"Yes, service is available":"Outside standard coverage"}</b><small>Nearest area: {result.nearest}, {result.distance.toFixed(1)} km away. {result.available?"You are inside its 15 km radius.":"Call us and we may still arrange service."}</small></span></div>}{status==="denied"&&<div className="geo-result unavailable"><XCircle/><span><b>Location permission denied</b><small>Allow location access in browser settings, then try again.</small></span></div>}{status==="unsupported"&&<div className="geo-result unavailable"><XCircle/><span><b>Location unavailable</b><small>Your browser does not support location detection.</small></span></div>}{children&&<><div className="location-divider"><span>or type your location</span></div>{children}</>}</aside></div></section>
}
