"use client";
import {FormEvent,useMemo,useState} from "react";
import {CheckCircle2,LoaderCircle,MapPin,Search,XCircle} from "lucide-react";
import {coverageLabel,coveredLocalities,serviceAreas} from "@/data/serviceAreas";
import CoverageMap from "./CoverageMap";

type CheckResult={available:boolean;place:string;nearest:string;distance:number}|null;
const searchable=[...serviceAreas.map(a=>({name:a.name,searchTerms:a.searchTerms,lat:a.lat,lng:a.lng})),...coveredLocalities];
function distanceKm(aLat:number,aLng:number,bLat:number,bLng:number){const r=6371;const dLat=(bLat-aLat)*Math.PI/180;const dLng=(bLng-aLng)*Math.PI/180;const x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(x))}
function checkCoordinates(lat:number,lng:number,place:string):CheckResult{let nearest=serviceAreas[0];let min=Infinity;for(const area of serviceAreas){const distance=distanceKm(lat,lng,area.lat,area.lng);if(distance<min){min=distance;nearest=area}}return{available:min<=15,place,nearest:nearest.name,distance:min}}

export default function LocationChecker(){
 const [query,setQuery]=useState("");const [result,setResult]=useState<CheckResult>(null);const [loading,setLoading]=useState(false);const [lookupError,setLookupError]=useState("");
 const matches=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return searchable.slice(0,6);return searchable.filter(a=>a.name.toLowerCase().includes(q)||a.searchTerms.some(t=>t.toLowerCase().includes(q))).slice(0,7)},[query]);
 function choose(place:(typeof searchable)[number]){setQuery(place.name);setLookupError("");setResult(checkCoordinates(place.lat,place.lng,place.name))}
 async function submit(e:FormEvent){e.preventDefault();const q=query.trim();if(!q)return;setLookupError("");const known=searchable.find(a=>a.name.toLowerCase()===q.toLowerCase()||a.searchTerms.some(t=>t.toLowerCase()===q.toLowerCase()));if(known){choose(known);return}setLoading(true);setResult(null);try{const response=await fetch(`/api/geocode?q=${encodeURIComponent(q)}`);const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.message);setResult(checkCoordinates(data.lat,data.lng,q))}catch(error){setLookupError(error instanceof Error?error.message:"Could not check this location") }finally{setLoading(false)}}
 return <section className="location-check"><div className="container"><CoverageMap><div className="location-tool"><form onSubmit={submit}><MapPin/><input value={query} onChange={e=>{setQuery(e.target.value);setResult(null);setLookupError("")}} placeholder="Town, village, sector or location" aria-label="Your location"/><button type="submit" disabled={loading}>{loading?<LoaderCircle className="spin"/>:<Search/>} Check</button></form>{query&&result===null&&!loading&&<div className="location-suggestions">{matches.length?matches.map(a=><button key={a.name} onClick={()=>choose(a)}><MapPin/> {a.name}<small>Check radius</small></button>):<span>Press Check to calculate coverage for “{query}”.</span>}</div>}{result&&<div className={result.available?"availability yes":"availability no"}>{result.available?<CheckCircle2/>:<XCircle/>}<span><b>{result.available?`Yes, we serve ${result.place}`:`${result.place} is outside standard coverage`}</b><small>Nearest service area: {result.nearest} ({result.distance.toFixed(1)} km). {result.available?"This location is within the 15 km service radius.":"Call us—we may still be able to arrange a technician."}</small></span></div>}{lookupError&&<div className="availability no"><XCircle/><span><b>We could not locate “{query}”</b><small>{lookupError}. Try adding the district or nearby sector.</small></span></div>}</div></CoverageMap><p className="coverage-footnote">Service is available {coverageLabel}; exact address confirmation may be required.</p></div></section>
}
